export const SIH_METADATA = {
  projectName: 'WeatherGPT',
  problemStatementId: '26068',
  problemStatementTitle: 'WeatherGPT: Conversational AI for Weather Forecasting, Alerts, and Climate Information',
  organization: 'Ministry of Earth Sciences (MoES)',
  department: 'India Meteorological Department (IMD)',
  theme: 'Disaster Management',
  edition: 'Smart India Hackathon 2026',
  version: '1.0.0-phase1-preview',
};

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
];

export const DEFAULT_LOCATIONS = [
  {
    id: 'kolkata',
    name: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5726,
    lon: 88.3639,
    stationCode: 'VECC',
    elevationMeters: 9,
    isFavorite: true,
  },
  {
    id: 'bhubaneswar',
    name: 'Bhubaneswar',
    district: 'Khurda',
    state: 'Odisha',
    lat: 20.2961,
    lon: 85.8245,
    stationCode: 'VEBS',
    elevationMeters: 45,
    isFavorite: true,
  },
  {
    id: 'delhi',
    name: 'New Delhi',
    district: 'Central Delhi',
    state: 'Delhi NCR',
    lat: 28.6139,
    lon: 77.2090,
    stationCode: 'VIDP',
    elevationMeters: 216,
    isFavorite: true,
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    lat: 19.0760,
    lon: 72.8777,
    stationCode: 'VABB',
    elevationMeters: 14,
    isFavorite: true,
  },
  {
    id: 'chennai',
    name: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0827,
    lon: 80.2707,
    stationCode: 'VOMM',
    elevationMeters: 6,
    isFavorite: false,
  },
  {
    id: 'guwahati',
    name: 'Guwahati',
    district: 'Kamrup',
    state: 'Assam',
    lat: 26.1445,
    lon: 91.7362,
    stationCode: 'VEGT',
    elevationMeters: 55,
    isFavorite: false,
  },
];
